IGF = 'IGF-1 ng/ml (N: 100-311)'
VITAMINE_D = 'vitamin 25-OH D ng/ml'
PROLACTIN = 'prolactin'
PCO = 'PCO 0-healthy control, 1-PCOS, 2-FHA 3-POF, 4-High Andro'

CLASS_NAMES = ['healthy', 'PCOS', 'FHA', 'High Andro']


CATEGORICAL_ATTRIBUTES = [
    'PCO 0-healthy control, 1-PCOS, 2-FHA 3-POF, 4-High Andro', 'Hypertension', 'WC>88', 'WHR>0,85 (WHO)', 'WHR>0,8 (NIDDK)', 'WHTR>0,5', 
    'overweight/obesity 0-normal/low, 1-overweight, 2-obesity',
    'irregular cycles (0-nie, 1-tak)', 'ovulation (0-brak, 1-obecna)', 'PCO ovary morfology in USG (0-brak, 1--obecna)',
    'stromal hypertrophy in ovary (0-brak, 1-obecny)', 'acne', 'hirsutism', 'hyperandrogenism', 'elevated DHT', 'hypothyroidism', 'nodules 0-lack, 1-RL,  2-LL, 3-both', 'chronic thyroiditis',
    'follicules >12', 
    # 'hyperlipidemia', 'elevated LDL and TG', 
    'CHOL>200', 'HDL<50', 'LDL>135', 'SHBG>110',
    # 'TG>150', 'Impaired Fasting Glucose ', 'Impaired Glucose Tolerance', 
    # 'month of birth', 'quarter of the year',
    ]



CONTINUOUS_ATTRIBUTES = ['IGF-1 ng/ml (N: 100-311)',
 'proBNP',
 'AMH (ng/ml) *7,14=pmol/l',
 'weight',
 'height (cm)',
 'BMI',
 'systolic BP (ciśnienie skurczowe)',
 'diastolic BP (ciśnienie rozskurczowe)',
 'Waist Circumference (WC)',
 'Hip Circumference (HC)',
 'WHR (Waist/Hip ratio)',
 'WHTR (Waist/Height Ratio)',
 'FG score (Ferriman-Gallway score - stopień androgenizacji)',
 'Volume of the thyroid  Right Lobe',
 'Volume of the thyroid  Left Lobe',
 'thyroid volume',
 'Vole of the Right Ovary',
 'Volume of the  Left Ovary',
 'ovaries volume - total',
 'WBC x10^3/ul',
 'neutrophil x10^3/ul',
 'lymphocytes x10^3/ul',
 'monocytes x10^3/ul',
 'eosinocytes x10^3/ul',
 'basophils x10^3/ul',
 '% neutrophil ',
 '% lymphocytes ',
 '% monocytes',
 '%eosinocytes ',
 '%basophils ',
 'RBC x10^6ul',
 'Hemoglobin [g/dl]',
 'hematocrit [%]',
 'HTC/Hb',
 'MCV fl',
 'MCH pg',
 'MCHC g/dl',
 'RDW-CV %',
#  'NRBC x10^3/ul',
 'PLT x10^3/ul',
 'PDW fl',
 'MPV fl',
 'P-LCR %',
 'PLT/WBC',
 'MPV/PLT',
 'PLR',
 'limf/mono',
 'NLR (stosunek neutrofili do limfocytów)',
 'L/WCC (leukocyty do całkowitej liczby krwinek białych)',
 'eos/leukocyty',
 'sodium mmol/l',
 'potassium mmol/l',
 'calcium mg/dl',
 'phosphorus mg/dl',
 'creatinine mg/dl',
 'CRP mg/l',
 'ALT U/l',
 'AST U/l',
 'Bilirubin mg/dl',
#  'CHOL mg/dl ',
 'CHOL mmol/l',
#  ' HDL mg/dl',
 'HDL mmol/l',
#  'LDL mg/dl',
 'LDL mmol/l',
#  'TG',
 'TG mmol/l',
 'Atherogenic index (AI) (LDL-C/HDL-C) ',
 'coronary risk index (CRI) (TG/HDL-C)',
 'VAI - Visceral adiposity index',
 'BAI - Body adiposity index',
 'LAP INDEX - Lipid accumulation product index',
 'TyG Index - Trigliceride-glucose index',
 'AIP -Atherogenic index of plasma',
 'UIBC ug/dl',
 'ferrum ug/dl',
 'TIBC',
 'TSAT',
 'ferritin ng/ml',
 'glucose 0 mg/dl',
 'glucose  120 mg/dl',
 'insulin 0 uU/ml',
 'Insulin 120 uU/ml',
 'HOMA',
 'Matsuda',
 'QUICKI (N<0,357)',
 'TSH mIU/L',
 'FT3 pmol/l',
 'FT4 pmol/l',
 'Anty-TPO IU/ml',
 'Anty-TG IU/ml',
 'FSH mlU/ml',
 'LH',
 'LH/FSH',
 'prolactin',
 'DHEA-S ug/dl',
 'testosterone nmol/l',
 'T (ng/ml)',
 'T/SHBG',
 'E(pg/ml)/T(ng/ml)/',
 'Parathormone pg/ml',
 'cortisol nmol/l  8:00',
 'cortisol nmol/l 18:00',
 'Estradiol pg/ml',
 'SHBG nmol/l',
 'FTI (free testosterone index)',
 'ACTH pg/ml',
 'HbA1c %',
 'vitamin 25-OH D ng/ml',
 'Androstendione ng/ml',
 '17-OH-progesterone ng/ml',
 'Dihydrotestosterone pg/ml (N<368)',
 'Testosterone/DHT',
 'T/A (testosterone/androstendione)',
 'age']


# parametry związane z układem krążenia i ryzykiem jego chorób
circulatory_system_attributes = [
    'proBNP', 'systolic BP (ciśnienie skurczowe)', 'diastolic BP (ciśnienie rozskurczowe)', 'Hypertension', 
    # 'hyperlipidemia', 
    # 'elevated LDL and TG',
    'CHOL mg/dl ', 'CHOL mmol/l', 'CHOL>200', ' HDL mg/dl', 'HDL mmol/l', 'HDL<50', 'LDL mg/dl', 'LDL mmol/l', 'LDL>135', 'TG', 'TG mmol/l', 
    # 'TG>150',
    'Atherogenic index (AI) (LDL-C/HDL-C) ', 'coronary risk index (CRI) (TG/HDL-C)', 'VAI - Visceral adiposity index', 'BAI - Body adiposity index',
    'LAP INDEX - Lipid accumulation product index', 'TyG Index - Trigliceride-glucose index', 'AIP -Atherogenic index of plasma',
    ]
# hormony płciowe plus morfologia jajnika
sex_hormones_attributes = [
    'AMH (ng/ml) *7,14=pmol/l', 'irregular cycles (0-nie, 1-tak)', 'ovulation (0-brak, 1-obecna)', 'PCO ovary morfology in USG (0-brak, 1--obecna)',
    'stromal hypertrophy in ovary (0-brak, 1-obecny)', 'acne', 'hirsutism', 'FG score (Ferriman-Gallway score - stopień androgenizacji)', 'hyperandrogenism', 'elevated DHT',
    'Vole of the Right Ovary', 'Volume of the  Left Ovary', 'ovaries volume - total', 'follicules >12', 'FSH mlU/ml', 'LH', 'LH/FSH', 'DHEA-S ug/dl', 'testosterone nmol/l',
    'T (ng/ml)', 'T/SHBG', 'E(pg/ml)/T(ng/ml)/', 'Estradiol pg/ml', 'SHBG nmol/l', 'SHBG>110', 'FTI (free testosterone index)', 'Androstendione ng/ml', '17-OH-progesterone ng/ml',
    'Dihydrotestosterone pg/ml (N<368)', 'Testosterone/DHT', 'T/A (testosterone/androstendione)',
    ]
# gospodarka węglowodanowa (włączając oporność i wrazliwość na insulinę)
carbohydrate_metabolism_attributes = [
    'glucose 0 mg/dl', 'glucose  120 mg/dl', 'insulin 0 uU/ml', 'Insulin 120 uU/ml', 'HOMA', 'Matsuda', 'QUICKI (N<0,357)', 
    # 'Impaired Fasting Glucose ', 'Impaired Glucose Tolerance',
    ]
# parametry antropometryczne
anthropometric_attributes = [
    'weight', 'height (cm)', 'BMI', 'Waist Circumference (WC)', 'WC>88', 'Hip Circumference (HC)', 'WHR (Waist/Hip ratio)', 'WHR>0,85 (WHO)',
    'WHR>0,8 (NIDDK)', 'WHTR (Waist/Height Ratio)', 'WHTR>0,5', 'overweight/obesity 0-normal/low, 1-overweight, 2-obesity',
    ]
# parametry tarczycowe
thyroid_attributes = [
    'hypothyroidism', 'Volume of the thyroid  Right Lobe', 'Volume of the thyroid  Left Lobe', 'thyroid volume', 'nodules 0-lack, 1-RL,  2-LL, 3-both',
    'chronic thyroiditis', 'TSH mIU/L', 'FT3 pmol/l', 'FT4 pmol/l', 'Anty-TPO IU/ml', 'Anty-TG IU/ml',
    ]
# parametry zapalne
inflammatory_attributes = [
    'WBC x10^3/ul', 'neutrophil x10^3/ul', 'lymphocytes x10^3/ul', 'monocytes x10^3/ul', 'eosinocytes x10^3/ul', 'basophils x10^3/ul', '% neutrophil ', '% lymphocytes ',
    '% monocytes', '%eosinocytes ', '%basophils ', 'RBC x10^6ul', 'Hemoglobin [g/dl]', 'hematocrit [%]', 'HTC/Hb', 'MCV fl', 'MCH pg', 'MCHC g/dl', 'RDW-CV %', 
    # 'NRBC x10^3/ul',
    'PLT x10^3/ul', 'PDW fl', 'MPV fl', 'P-LCR %', 'PLT/WBC', 'MPV/PLT', 'PLR', 'limf/mono', 'NLR (stosunek neutrofili do limfocytów)',
    'L/WCC (leukocyty do całkowitej liczby krwinek białych)', 'eos/leukocyty', 'CRP mg/l',
    ]
#  gospodarka żelazowa
iron_attributes = ['UIBC ug/dl', 'ferrum ug/dl', 'TIBC', 'TSAT', 'ferritin ng/ml']
# gospodarka wapniowo-fosforanowa
calcium_attributes = ['calcium mg/dl', 'phosphorus mg/dl', 'Parathormone pg/ml']

attribute_groups = [
    circulatory_system_attributes, sex_hormones_attributes, carbohydrate_metabolism_attributes, anthropometric_attributes,
    thyroid_attributes, inflammatory_attributes, iron_attributes, calcium_attributes,
    ]


vitamin_d_associated_features = ['creatinine mg/dl', 'Parathormone pg/ml', 'phosphorus mg/dl']
igf_associated_features = ['HOMA', 'QUICKI (N<0,357)']
prolactin_associated_features = ['LH', 'cortisol nmol/l  8:00', '17-OH-progesterone ng/ml', 'T/SHBG', 'hyperandrogenism', 
                                 'PCO ovary morfology in USG (0-brak, 1--obecna)', 'LH/FSH', 'hirsutism', 'Testosterone/DHT', 'follicules >12',
                                 'Volume of the Left Ovary', 'testosterone nmol/l', 'Androstendione ng/ml']



index_features = [
    'LAP INDEX - Lipid accumulation product index',
    'VAI - Visceral adiposity index',
    'BAI - Body adiposity index',
    'TyG Index - Trigliceride-glucose index',
    'AIP -Atherogenic index of plasma',
    'Atherogenic index (AI) (LDL-C/HDL-C) ',
    'coronary risk index (CRI) (TG/HDL-C)',
    'FTI (free testosterone index)',
]



columns_for_one_hot_encoding = {'PCO 0-healthy control, 1-PCOS, 2-FHA 3-POF, 4-High Andro': 'PCO',
                             'overweight/obesity 0-normal/low, 1-overweight, 2-obesity': 'overweight',
                             'nodules 0-lack, 1-RL,  2-LL, 3-both': 'nodules',
                             'quarter of the year': 'birth_quarter',
                             'month of birth': 'birth_month',
                             }

new_column_names_map = {
    'PCO_0': '0_healthy_control',
    'PCO_1': '1_PCOS',
    'PCO_2': '2_FHA',
    'PCO_3': '3_POF',
    'PCO_4': '4_High_Andro',
    'overweight_0': '0_normal_weight',
    'overweight_1': '1_overweight',
    'overweight_2': '2_obesity',
    'nodules_0': 'no_nodules',
    'nodules_1': 'nodules_right',
    'nodules_2': 'nodules_left',
    'nodules_3': 'nodules_both_sides',
    }


vit_d_mutual_info_best_features = ['FTI (free testosterone index)', 'Hip Circumference (HC)',
        'PLT/WBC', 'PDW fl', 'BMI', 'Androstendione ng/ml',
        'Estradiol pg/ml', 'RBC x10^6ul', 'T/SHBG', 'HDL mmol/l',
        'IGF-1 ng/ml (N: 100-311)', 'age', 'P-LCR %',
        'FG score (Ferriman-Gallway score - stopień androgenizacji)',
        'testosterone nmol/l', 'Volume of the thyroid  Right Lobe',
        'basophils x10^3/ul', 'glucose  120 mg/dl', 'T (ng/ml)',
        'Anty-TPO IU/ml', 'Volume of the  Left Ovary', 'HbA1c %',
        'sodium mmol/l', 'NLR (stosunek neutrofili do limfocytów)',
        'overweight/obesity 0-normal/low, 1-overweight, 2-obesity',
        'PCO ovary morfology in USG (0-brak, 1--obecna)', '% monocytes',
        'DHEA-S ug/dl',
        'PCO 0-healthy control, 1-PCOS, 2-FHA 3-POF, 4-High Andro',
        'AMH (ng/ml) *7,14=pmol/l', 'proBNP', 'insulin 0 uU/ml', 'MPV fl',
        'HDL<50', 'WBC x10^3/ul', 'CRP mg/l', 'UIBC ug/dl', 'SHBG>110',
        'monocytes x10^3/ul', 'hypothyroidism',
        'LAP INDEX - Lipid accumulation product index',
        'Insulin 120 uU/ml', 'MPV/PLT', 'ferrum ug/dl',
        'TyG Index - Trigliceride-glucose index', 'potassium mmol/l',
        'HOMA', 'TSAT', 'FSH mlU/ml', 'E(pg/ml)/T(ng/ml)/',
        'eosinocytes x10^3/ul', 'QUICKI (N<0,357)',
        'cortisol nmol/l  8:00', 'chronic thyroiditis', 'thyroid volume',
        'cortisol nmol/l 18:00', 'TG mmol/l', 'TSH mIU/L', 'height (cm)',
        'weight', 'stromal hypertrophy in ovary (0-brak, 1-obecny)', 'PLR',
        'WHR>0,85 (WHO)', '17-OH-progesterone ng/ml', 'Hemoglobin [g/dl]',
        'ovaries volume - total']


vit_d_permutation_importance_best_features = ['QUICKI (N<0,357)', 'WHTR (Waist/Height Ratio)', 'PLT x10^3/ul',
       'Hip Circumference (HC)', 'AIP -Atherogenic index of plasma',
       'TyG Index - Trigliceride-glucose index',
       'BAI - Body adiposity index', 'TG mmol/l', 'eos/leukocyty', 'HOMA',
       'lymphocytes x10^3/ul', 'NLR (stosunek neutrofili do limfocytów)',
       'L/WCC (leukocyty do całkowitej liczby krwinek białych)',
       'coronary risk index (CRI) (TG/HDL-C)', 'T (ng/ml)', 'PLT/WBC',
       'insulin 0 uU/ml', 'PLR', 'ovaries volume - total',
       '%eosinocytes ', 'testosterone nmol/l', 'MPV/PLT',
       'neutrophil x10^3/ul', 'LH', 'WBC x10^3/ul', 'weight', 'LH/FSH',
       'FSH mlU/ml', 'LAP INDEX - Lipid accumulation product index',
       'MPV fl', 'Vole of the Right Ovary', 'T/SHBG', 'ferrum ug/dl',
       'glucose 0 mg/dl']


prolactin_mutual_info_best_features = ['glucose 0 mg/dl', 'WBC x10^3/ul', 'hematocrit [%]', 'FT4 pmol/l',
        'SHBG nmol/l', 'weight', 'DHEA-S ug/dl', 'ferritin ng/ml',
        'ACTH pg/ml', 'WHTR (Waist/Height Ratio)', '%basophils ',
        'Anty-TPO IU/ml', 'potassium mmol/l', 'BAI - Body adiposity index',
        'lymphocytes x10^3/ul', 'basophils x10^3/ul', 'FT3 pmol/l',
        'E(pg/ml)/T(ng/ml)/', 'ferrum ug/dl',
        'PCO 0-healthy control, 1-PCOS, 2-FHA 3-POF, 4-High Andro', 'age',
        'CRP mg/l',
        'overweight/obesity 0-normal/low, 1-overweight, 2-obesity',
        'systolic BP (ciśnienie skurczowe)', 'CHOL mmol/l', 'RBC x10^6ul',
        'neutrophil x10^3/ul', 'BMI', 'eosinocytes x10^3/ul', 'MCV fl',
        'Matsuda', 'FTI (free testosterone index)',
        'LAP INDEX - Lipid accumulation product index', 'TIBC', 'HOMA',
        'WC>88', 'IGF-1 ng/ml (N: 100-311)', 'QUICKI (N<0,357)',
        'height (cm)', 'Atherogenic index (AI) (LDL-C/HDL-C) ', 'AST U/l',
        'glucose  120 mg/dl', 'CHOL>200', 'MPV fl',
        'coronary risk index (CRI) (TG/HDL-C)',
        'FG score (Ferriman-Gallway score - stopień androgenizacji)',
        'PLT x10^3/ul', 'diastolic BP (ciśnienie rozskurczowe)',
        'monocytes x10^3/ul', 'phosphorus mg/dl', 'T (ng/ml)',
        'ovulation (0-brak, 1-obecna)', 'Hemoglobin [g/dl]',
        'Parathormone pg/ml', 'RDW-CV %', 'Hip Circumference (HC)',
        'HDL mmol/l', 'Hypertension', 'acne',
        'TyG Index - Trigliceride-glucose index', 'insulin 0 uU/ml',
        'Bilirubin mg/dl', 'LDL>135', 'ALT U/l', 'WHR (Waist/Hip ratio)',
        'Waist Circumference (WC)', 'WHTR>0,5',
        'VAI - Visceral adiposity index',
        'L/WCC (leukocyty do całkowitej liczby krwinek białych)',
        'nodules 0-lack, 1-RL,  2-LL, 3-both', 'SHBG>110',
        'ovaries volume - total', 'irregular cycles (0-nie, 1-tak)',
        'LDL mmol/l', 'sodium mmol/l']


prolactin_permutation_importance_best_features = ['neutrophil x10^3/ul', 'TyG Index - Trigliceride-glucose index',
        'TG mmol/l', 'Waist Circumference (WC)', 'insulin 0 uU/ml',
        'NLR (stosunek neutrofili do limfocytów)', 'eos/leukocyty', 'HOMA',
        'WHTR (Waist/Height Ratio)', 'WBC x10^3/ul',
        'Atherogenic index (AI) (LDL-C/HDL-C) ', 'LDL mmol/l',
        'Hemoglobin [g/dl]', 'coronary risk index (CRI) (TG/HDL-C)',
        '%eosinocytes ', 'weight', 'Estradiol pg/ml',
        'AIP -Atherogenic index of plasma',
        'LAP INDEX - Lipid accumulation product index',
        'Hip Circumference (HC)', 'MPV/PLT', 'P-LCR %', 'hematocrit [%]',
        'PLR', 'ACTH pg/ml', 'HTC/Hb', 'E(pg/ml)/T(ng/ml)/', 'HDL mmol/l',
        'PLT/WBC', 'Matsuda', 'monocytes x10^3/ul',
        'VAI - Visceral adiposity index', 'limf/mono',
        'lymphocytes x10^3/ul', 'FT4 pmol/l', 'T (ng/ml)',
        '% lymphocytes ', 'RBC x10^6ul', 'CHOL mmol/l', 'WHTR>0,5',
        'DHEA-S ug/dl', 'TSH mIU/L', 'QUICKI (N<0,357)', '% monocytes',
        '%basophils ', 'PLT x10^3/ul', 'WHR (Waist/Hip ratio)',
        'basophils x10^3/ul', 'Volume of the thyroid  Left Lobe',
        'nodules 0-lack, 1-RL,  2-LL, 3-both', 'AST U/l', 'MCV fl',
        'Parathormone pg/ml', 'diastolic BP (ciśnienie rozskurczowe)']


igf_mutual_info_best_features = ['TIBC', 'age', 'acne', 'coronary risk index (CRI) (TG/HDL-C)',
        'DHEA-S ug/dl', 'AIP -Atherogenic index of plasma',
        'Volume of the thyroid  Right Lobe', 'basophils x10^3/ul',
        'PCO 0-healthy control, 1-PCOS, 2-FHA 3-POF, 4-High Andro',
        'T/SHBG', 'diastolic BP (ciśnienie rozskurczowe)',
        'Vole of the Right Ovary', 'ovaries volume - total',
        'glucose  120 mg/dl', 'RBC x10^6ul', 'MCH pg',
        'Volume of the thyroid  Left Lobe',
        'FTI (free testosterone index)',
        'L/WCC (leukocyty do całkowitej liczby krwinek białych)',
        'glucose 0 mg/dl', 'Atherogenic index (AI) (LDL-C/HDL-C) ',
        'FT3 pmol/l', 'cortisol nmol/l  8:00', 'HTC/Hb', '%basophils ',
        'ovulation (0-brak, 1-obecna)', 'insulin 0 uU/ml',
        'WHTR (Waist/Height Ratio)', 'TSH mIU/L',
        'VAI - Visceral adiposity index', '% lymphocytes ',
        'lymphocytes x10^3/ul', 'MPV fl', 'ferrum ug/dl',
        'AMH (ng/ml) *7,14=pmol/l', 'hypothyroidism', 'Matsuda',
        'SHBG nmol/l', 'PCO ovary morfology in USG (0-brak, 1--obecna)',
        'BMI', 'HDL<50', 'HbA1c %', 'Hypertension', 'UIBC ug/dl',
        'hyperandrogenism', 'potassium mmol/l', 'Waist Circumference (WC)',
        'PLT x10^3/ul', 'vitamin 25-OH D ng/ml',
        'Volume of the  Left Ovary', 'WHR>0,8 (NIDDK)',
        'Dihydrotestosterone pg/ml (N<368)', 'LDL mmol/l', 'prolactin',
        'stromal hypertrophy in ovary (0-brak, 1-obecny)',
        'WHR>0,85 (WHO)', 'Androstendione ng/ml',
        'FG score (Ferriman-Gallway score - stopień androgenizacji)',
        'MPV/PLT',
        'overweight/obesity 0-normal/low, 1-overweight, 2-obesity',
        'PLT/WBC', 'nodules 0-lack, 1-RL,  2-LL, 3-both', 'follicules >12',
        'monocytes x10^3/ul', 'systolic BP (ciśnienie skurczowe)',
        'WHR (Waist/Hip ratio)', 'Hemoglobin [g/dl]', 'PDW fl', 'MCV fl',
        'LH/FSH', 'FSH mlU/ml', 'Anty-TPO IU/ml', 'hematocrit [%]']


igf_permutation_importance_best_features = ['insulin 0 uU/ml', 'age', 'BMI',
        'L/WCC (leukocyty do całkowitej liczby krwinek białych)',
        'phosphorus mg/dl', '% neutrophil ', 'Estradiol pg/ml',
        'FT3 pmol/l', '% lymphocytes ', 'LDL mmol/l', 'Bilirubin mg/dl',
        'thyroid volume', 'potassium mmol/l', 'PDW fl',
        'NLR (stosunek neutrofili do limfocytów)', 'hematocrit [%]',
        'weight', 'LH/FSH', 'Volume of the thyroid  Left Lobe',
        'cortisol nmol/l  8:00', 'P-LCR %', 'FSH mlU/ml', 'Matsuda',
        'calcium mg/dl', 'MPV fl', 'Volume of the thyroid  Right Lobe',
        '17-OH-progesterone ng/ml', 'WHTR (Waist/Height Ratio)',
        'Hip Circumference (HC)', 'Volume of the  Left Ovary',
        'glucose 0 mg/dl', 'T/A (testosterone/androstendione)',
        'Atherogenic index (AI) (LDL-C/HDL-C) ',
        'systolic BP (ciśnienie skurczowe)', 'Androstendione ng/ml',
        'Waist Circumference (WC)', 'BAI - Body adiposity index',
        'TSH mIU/L', 'LH', 'AST U/l', 'SHBG nmol/l',
        'AIP -Atherogenic index of plasma', 'ferrum ug/dl',
        'creatinine mg/dl', 'glucose  120 mg/dl', 'CRP mg/l',
        'Insulin 120 uU/ml', 'TSAT', 'ALT U/l',
        'FTI (free testosterone index)', 'ACTH pg/ml',
        'monocytes x10^3/ul', 'diastolic BP (ciśnienie rozskurczowe)',
        'CHOL mmol/l', 'lymphocytes x10^3/ul', 'UIBC ug/dl',
        'TyG Index - Trigliceride-glucose index', 'PLT x10^3/ul', 'T/SHBG',
        'ovulation (0-brak, 1-obecna)', 'TG mmol/l', 'RBC x10^6ul', 'acne',
        'E(pg/ml)/T(ng/ml)/', 'HDL mmol/l', '% monocytes',
        'ovaries volume - total', 'testosterone nmol/l', 'prolactin',
        'T (ng/ml)', 'stromal hypertrophy in ovary (0-brak, 1-obecny)',
        'DHEA-S ug/dl', 'LAP INDEX - Lipid accumulation product index',
        'Testosterone/DHT', 'FT4 pmol/l', 'ferritin ng/ml',
        'Dihydrotestosterone pg/ml (N<368)', 'AMH (ng/ml) *7,14=pmol/l',
        'Hemoglobin [g/dl]', 'HTC/Hb',
        'coronary risk index (CRI) (TG/HDL-C)', 'eosinocytes x10^3/ul',
        'Parathormone pg/ml', 'MPV/PLT', 'PLR']